name: Sync Backend and Deploy

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main

jobs:
  update_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Frontend Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Pull Latest Backend
        run: |
          rm -rf backend  # Remove old backend (if any)
          git clone https://github.com/GEMINI-Breeding/photorch backend  

      - name: Push updates
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add backend
          git commit -m "Auto-update backend to latest" || exit 0
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/ktrizzo/photorch-app.git main

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          pip install streamlit 

      - name: Deploy Streamlit App
        run: |
          python -m streamlit run app.py --server.headless true

