name: Sync Backend and Deploy

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main  # Runs when the main branch is updated

jobs:
  update_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Frontend Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true  # If using submodules

      - name: Pull Latest Backend
        run: |
          rm -rf backend  # Remove old backend (if any)
          git clone https://github.com/GEMINI-Breeding/photorch backend  # Clone latest backend

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add backend
          git commit -m "Auto-update backend to latest" || echo "No changes to commit"
          git push origin main

      - name: Deploy Streamlit App
        run: |
          streamlit run app.py --server.headless true  # Replace with your deployment command
